### ISSUE TITLE
Config volume is not available in initContainer

### ISSUE THREAD

**Issue by zdenekletko** [WanderaOrg/scccmd#30]
Trying to use the config volume created by the scccmd in k8s descriptors like
```
      initContainers:
      - name: test-init-s3-bucket
        image: alpine:3.6
        volumeMounts:
        - name: config
          mountPath: /config
        command:
          - sh
          - '-c'
          - 'echo HelloInit && cat /config/config.yaml'
      containers: ...
```
leads to
```
The Deployment "..." is invalid: spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "config-volume"
```
